[project]
name = "utils"
version = "0.1.0"
description = "AI experiments"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "modal>=0.73.67",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "polars>=1.23.0",
    "scikit-learn>=1.6.1",
    "torch>=2.6.0",
]

[dependency-groups]
dev = [
    "ruff>=0.9.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/utils"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "B", "C", "D", "T"]
ignore = [
    "E501",
    "D100", "D101", "D102", "D103", "D104", "D105", "D107", "D211", "D212", "D413",
    "T201",
]

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = [
    "C408", "C416",
    "D205", "D400", "D401", "D415",
    "E731",
    "F811",
]
