name: Lint & Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.3"

      - name: Install dependencies
        run: uv sync

      - name: Run Ruff
        run: uv run ruff check
